exclude: .*migrations\/.*
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3.10
        args: [--line-length=120, --skip-string-normalization]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
